version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: sipwave_db
    restart: unless-stopped
    ports:
      - "5432:5432" 
    networks:
      - backing-services
    volumes:
      - /tmp:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  backing-services:
    driver: bridge