version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: sipwave_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - sipwave_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 

  asterisk:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "8089:8089" # wss (WebSocket)
    networks:
      - sipwave_network
    restart: unless-stopped

networks:
  sipwave_network:
    driver: bridge